# Generated by Django 5.2.5 on 2025-08-25 09:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.CharField(blank=True, choices=[('Head of Sales', 'Head of Sales'), ('Facilitator', 'Facilitator'), ('Product Brand Manager', 'Product Brand Manager'), ('Corporate Manager', 'Corporate Manager'), ('Corporate Officer', 'Corporate Officer'), ('Zonal Sales Executive', 'Zonal Sales Executive'), ('Mobile Sales Officer', 'Mobile Sales Officer'), ('Desk Sales Officer', 'Desk Sales Officer'), ('Admin', 'Admin')], max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Coast Zone', 'Coast Zone'), ('Corporate', 'Corporate'), ('Central Zone', 'Central Zone'), ('Southern Zone', 'Southern Zone'), ('Northern Zone', 'Northern Zone'), ('Lake Zone', 'Lake Zone')], max_length=100, null=True)),
                ('branch', models.CharField(blank=True, choices=[('Chanika', 'Chanika'), ('Mikocheni', 'Mikocheni'), ('Morogoro', 'Morogoro'), ('Zanzibar', 'Zanzibar'), ('ANDO HQ', 'ANDO HQ'), ('Dodoma', 'Dodoma'), ('Singida', 'Singida'), ('Tabora', 'Tabora'), ('Mbeya', 'Mbeya'), ('Tunduma', 'Tunduma'), ('Arusha', 'Arusha'), ('Moshi', 'Moshi'), ('Mwanza', 'Mwanza'), ('Geita', 'Geita')], max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Tanzanian phone number (e.g. +255712345678 or 0712345678)', regex='^(?:\\+255|0)[67][0-9]\\d{7}$')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('serial_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyVisitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('serial_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionline', models.CharField(choices=[('RESIN_ROOFING_SHEETS', 'RESIN ROOFING SHEETS'), ('ROOF_PAINT', 'ROOF PAINT'), ('UPVC', 'UPVC'), ('WALL_COATING', 'WALL COATING'), ('ZEBRA_TILES', 'ZEBRA TILES')], default='RESIN_ROOFING_SHEETS', max_length=30)),
                ('client_name_or_company', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Owner', 'Owner'), ('Engineer', 'Engineer'), ('Contractor', 'Contractor')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_purpose', models.CharField(max_length=255)),
                ('meeting_outcome', models.CharField(max_length=255)),
                ('item_discussed', models.TextField(max_length=255)),
                ('is_order_quoted', models.BooleanField(default=False)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason_no_order', models.TextField(blank=True, null=True)),
                ('is_payment_collected', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason_no_payment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('daily_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='visits.dailyfollowup')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_status', models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10)),
                ('daily_followup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='visits.dailyfollowup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_status', models.CharField(choices=[('opened', 'Opened'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmite', 'Resubmite')], default='opened', max_length=10)),
                ('daily_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='visits.dailyvisitform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionline', models.CharField(blank=True, choices=[('RESIN_ROOFING_SHEETS', 'RESIN ROOFING SHEETS'), ('ROOF_PAINT', 'ROOF PAINT'), ('UPVC', 'UPVC'), ('WALL_COATING', 'WALL COATING'), ('ZEBRA_TILES', 'ZEBRA TILES')], max_length=30, null=True)),
                ('client_name_or_company', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Owner', 'Owner'), ('Engineer', 'Engineer'), ('Contractor', 'Contractor')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_purpose', models.CharField(max_length=255)),
                ('meeting_outcome', models.CharField(max_length=255)),
                ('item_discussed', models.TextField(max_length=255)),
                ('is_order_quoted', models.BooleanField(default=False)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason_no_order', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('daily_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visits.dailyvisitform')),
            ],
        ),
    ]
