# Generated by Django 5.2.5 on 2025-08-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newvisit',
            name='client_name_or_company',
        ),
        migrations.AddField(
            model_name='newvisit',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='customer.customercontact'),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='designation',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Engineer', 'Engineer'), ('Contractor', 'Contractor')], max_length=20, null=True),
        ),
    ]
