# Generated by Django 5.2.5 on 2025-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_newvisit_client_name_or_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvisit',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
