# Generated by Django 5.2.5 on 2025-08-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('visits', '0003_alter_newvisit_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='client_name_or_company',
        ),
        migrations.AddField(
            model_name='followup',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_contacts', to='customer.customercontact'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='productionline',
            field=models.CharField(blank=True, choices=[('RESIN_ROOFING_SHEETS', 'RESIN ROOFING SHEETS'), ('ROOF_PAINT', 'ROOF PAINT'), ('UPVC', 'UPVC'), ('WALL_COATING', 'WALL COATING'), ('ZEBRA_TILES', 'ZEBRA TILES')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
