# Generated by Django 5.2.5 on 2025-08-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_remove_followup_client_name_or_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
