# Generated by Django 5.2.5 on 2025-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='designation',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Engineer', 'Engineer'), ('Contractor', 'Contractor')], max_length=100),
        ),
    ]
